#############################################################################
# Makefile for building: QtFilter2D
# Generated by qmake (3.1) (Qt 5.15.15)
# Project:  QtFilter2D.pro
# Template: app
# Command: C:/Qt/5.15.15/bin/qmake.exe -o Makefile QtFilter2D.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:/Qt/5.15.15/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = C:/Qt/5.15.15/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = C:/Qt/5.15.15/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = midl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: QtFilter2D.pro C:/Qt/5.15.15/mkspecs/win32-g++/qmake.conf C:/Qt/5.15.15/mkspecs/features/spec_pre.prf \
		C:/Qt/5.15.15/mkspecs/qdevice.pri \
		C:/Qt/5.15.15/mkspecs/features/device_config.prf \
		C:/Qt/5.15.15/mkspecs/common/sanitize.conf \
		C:/Qt/5.15.15/mkspecs/common/gcc-base.conf \
		C:/Qt/5.15.15/mkspecs/common/g++-base.conf \
		C:/Qt/5.15.15/mkspecs/common/angle.conf \
		C:/Qt/5.15.15/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/5.15.15/mkspecs/common/windows-vulkan.conf \
		C:/Qt/5.15.15/mkspecs/common/g++-win32.conf \
		C:/Qt/5.15.15/mkspecs/common/windows-desktop.conf \
		C:/Qt/5.15.15/mkspecs/qconfig.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_ext_pcre2.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_edid_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_theme_support_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qdirect2d.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qicns.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qjpeg.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qminimal.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtga.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtiff.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qwbmp.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qwindows.pri \
		C:/Qt/5.15.15/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		C:/Qt/5.15.15/mkspecs/features/qt_functions.prf \
		C:/Qt/5.15.15/mkspecs/features/qt_config.prf \
		C:/Qt/5.15.15/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.15.15/mkspecs/features/spec_post.prf \
		C:/Qt/5.15.15/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.15.15/mkspecs/features/toolchain.prf \
		C:/Qt/5.15.15/mkspecs/features/default_pre.prf \
		C:/Qt/5.15.15/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.15.15/mkspecs/features/resolve_config.prf \
		C:/Qt/5.15.15/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.15.15/mkspecs/features/default_post.prf \
		C:/Qt/5.15.15/mkspecs/features/precompile_header.prf \
		C:/Qt/5.15.15/mkspecs/features/warn_on.prf \
		C:/Qt/5.15.15/mkspecs/features/qt.prf \
		C:/Qt/5.15.15/mkspecs/features/gc_binaries.prf \
		C:/Qt/5.15.15/mkspecs/features/resources_functions.prf \
		C:/Qt/5.15.15/mkspecs/features/resources.prf \
		C:/Qt/5.15.15/mkspecs/features/moc.prf \
		C:/Qt/5.15.15/mkspecs/features/win32/opengl.prf \
		C:/Qt/5.15.15/mkspecs/features/uic.prf \
		C:/Qt/5.15.15/mkspecs/features/qmake_use.prf \
		C:/Qt/5.15.15/mkspecs/features/file_copies.prf \
		C:/Qt/5.15.15/mkspecs/features/win32/windows.prf \
		C:/Qt/5.15.15/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.15.15/mkspecs/features/exceptions.prf \
		C:/Qt/5.15.15/mkspecs/features/yacc.prf \
		C:/Qt/5.15.15/mkspecs/features/lex.prf \
		QtFilter2D.pro \
		C:/Qt/5.15.15/plugins/platforms/qwindows.prl \
		C:/Qt/5.15.15/plugins/imageformats/qicns.prl \
		C:/Qt/5.15.15/plugins/imageformats/qjpeg.prl \
		C:/Qt/5.15.15/plugins/imageformats/qtga.prl \
		C:/Qt/5.15.15/plugins/imageformats/qtiff.prl \
		C:/Qt/5.15.15/plugins/imageformats/qwbmp.prl \
		C:/Qt/5.15.15/lib/Qt5Widgets.prl \
		C:/Qt/5.15.15/lib/Qt5Gui.prl \
		C:/Qt/5.15.15/lib/Qt5Core.prl \
		C:/Qt/5.15.15/lib/qtmain.prl \
		.qmake.stash \
		C:/Qt/5.15.15/mkspecs/features/build_pass.prf
	$(QMAKE) -o Makefile QtFilter2D.pro
C:/Qt/5.15.15/mkspecs/features/spec_pre.prf:
C:/Qt/5.15.15/mkspecs/qdevice.pri:
C:/Qt/5.15.15/mkspecs/features/device_config.prf:
C:/Qt/5.15.15/mkspecs/common/sanitize.conf:
C:/Qt/5.15.15/mkspecs/common/gcc-base.conf:
C:/Qt/5.15.15/mkspecs/common/g++-base.conf:
C:/Qt/5.15.15/mkspecs/common/angle.conf:
C:/Qt/5.15.15/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/5.15.15/mkspecs/common/windows-vulkan.conf:
C:/Qt/5.15.15/mkspecs/common/g++-win32.conf:
C:/Qt/5.15.15/mkspecs/common/windows-desktop.conf:
C:/Qt/5.15.15/mkspecs/qconfig.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_ext_pcre2.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_bootstrap_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_core.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_edid_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_network.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_openglextensions.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_openglextensions_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_theme_support_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qdirect2d.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qgenericbearer.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qicns.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qjpeg.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qminimal.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtga.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtiff.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qwbmp.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_qwindows.pri:
C:/Qt/5.15.15/mkspecs/modules/qt_plugin_windowsprintersupport.pri:
C:/Qt/5.15.15/mkspecs/features/qt_functions.prf:
C:/Qt/5.15.15/mkspecs/features/qt_config.prf:
C:/Qt/5.15.15/mkspecs/win32-g++/qmake.conf:
C:/Qt/5.15.15/mkspecs/features/spec_post.prf:
C:/Qt/5.15.15/mkspecs/features/exclusive_builds.prf:
C:/Qt/5.15.15/mkspecs/features/toolchain.prf:
C:/Qt/5.15.15/mkspecs/features/default_pre.prf:
C:/Qt/5.15.15/mkspecs/features/win32/default_pre.prf:
C:/Qt/5.15.15/mkspecs/features/resolve_config.prf:
C:/Qt/5.15.15/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/5.15.15/mkspecs/features/default_post.prf:
C:/Qt/5.15.15/mkspecs/features/precompile_header.prf:
C:/Qt/5.15.15/mkspecs/features/warn_on.prf:
C:/Qt/5.15.15/mkspecs/features/qt.prf:
C:/Qt/5.15.15/mkspecs/features/gc_binaries.prf:
C:/Qt/5.15.15/mkspecs/features/resources_functions.prf:
C:/Qt/5.15.15/mkspecs/features/resources.prf:
C:/Qt/5.15.15/mkspecs/features/moc.prf:
C:/Qt/5.15.15/mkspecs/features/win32/opengl.prf:
C:/Qt/5.15.15/mkspecs/features/uic.prf:
C:/Qt/5.15.15/mkspecs/features/qmake_use.prf:
C:/Qt/5.15.15/mkspecs/features/file_copies.prf:
C:/Qt/5.15.15/mkspecs/features/win32/windows.prf:
C:/Qt/5.15.15/mkspecs/features/testcase_targets.prf:
C:/Qt/5.15.15/mkspecs/features/exceptions.prf:
C:/Qt/5.15.15/mkspecs/features/yacc.prf:
C:/Qt/5.15.15/mkspecs/features/lex.prf:
QtFilter2D.pro:
C:/Qt/5.15.15/plugins/platforms/qwindows.prl:
C:/Qt/5.15.15/plugins/imageformats/qicns.prl:
C:/Qt/5.15.15/plugins/imageformats/qjpeg.prl:
C:/Qt/5.15.15/plugins/imageformats/qtga.prl:
C:/Qt/5.15.15/plugins/imageformats/qtiff.prl:
C:/Qt/5.15.15/plugins/imageformats/qwbmp.prl:
C:/Qt/5.15.15/lib/Qt5Widgets.prl:
C:/Qt/5.15.15/lib/Qt5Gui.prl:
C:/Qt/5.15.15/lib/Qt5Core.prl:
C:/Qt/5.15.15/lib/qtmain.prl:
.qmake.stash:
C:/Qt/5.15.15/mkspecs/features/build_pass.prf:
qmake: FORCE
	@$(QMAKE) -o Makefile QtFilter2D.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:/Users/pavlt/vs_files/.vscode/labs2/L17/qtfilter2d_plugin_import.cpp .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
